// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDduuPuUhe6tA2AePcjDlt2mbKXLniNS_o',
    appId: '1:563946212630:web:05a7b659dcb5b3444cd437',
    messagingSenderId: '563946212630',
    projectId: 'finalproject-f5e9e',
    authDomain: 'finalproject-f5e9e.firebaseapp.com',
    storageBucket: 'finalproject-f5e9e.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDmiHtF5NVE6IKQ1zV8IAdXWYJeZ4TVHys',
    appId: '1:563946212630:android:71169235d82f540b4cd437',
    messagingSenderId: '563946212630',
    projectId: 'finalproject-f5e9e',
    storageBucket: 'finalproject-f5e9e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAE29FF22TuJKqg4ouo64SI4PvceTDgc9Y',
    appId: '1:563946212630:ios:4953cc09c0e3a72f4cd437',
    messagingSenderId: '563946212630',
    projectId: 'finalproject-f5e9e',
    storageBucket: 'finalproject-f5e9e.appspot.com',
    iosClientId: '563946212630-rortb6afn5cukv6sqatq7akm5b0gge14.apps.googleusercontent.com',
    iosBundleId: 'com.example.eventPlanner',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAE29FF22TuJKqg4ouo64SI4PvceTDgc9Y',
    appId: '1:563946212630:ios:4953cc09c0e3a72f4cd437',
    messagingSenderId: '563946212630',
    projectId: 'finalproject-f5e9e',
    storageBucket: 'finalproject-f5e9e.appspot.com',
    iosClientId: '563946212630-rortb6afn5cukv6sqatq7akm5b0gge14.apps.googleusercontent.com',
    iosBundleId: 'com.example.eventPlanner',
  );
}
